export enum FlyRegion {
  AMSTERDAM = "ams",
  ATLANTA = "atl",
  CHICAGO = "ord",
  DALLAS = "dfw",
  FRANKFURT = "fra",
  HONG_KONG = "hkg",
  LONDON = "lhr",
  LOS_ANGELES = "lax",
  NEW_YORK = "ewr",
  PARIS = "cdg",
  SANTIAGO = "scl",
  SAO_PAULO = "gru",
  SINGAPORE = "sin",
  SYDNEY = "syd",
  TOKYO = "nrt",
  TORONTO = "yyz",
  WASHINGTON_DC = "iad",
}